### ISSUE TITLE
How long must I wait - using Shiny and the tidyverse to investigate queue waiting times

### ISSUE THREAD

**Issue by MikeKSmith** [mexindian/R-Users-Canterbury#1]
Hi.

I gave a presentation at the EARL conference in London this year around using the tidyverse packages (dplyr, tidy, ggplot2) and Shiny to allow me and anyone else using the app to investigate queue times for our high performance computing GRID at Pfizer. 

I'd be happy to reprise the presentation here.
Mike

**Comment by DataStrategist** [comment]
Yes, I saw you :) I gave the "Making International Development Data Not Useless" talk. 

Thanks for that.. the community is a bit young still... maybe next year or so we'll be ready for something thick like this :)

**Comment by MikeKSmith** [comment]
Ah, OK. Happy to be "on hold" for this one! ;-)
